name: Test
on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'Gemfile'
      - 'Rakefile'
      - 'omniauth-zoom-v2.gemspec'
      - '**/*.rb'
  schedule:
    - cron: '0 12 * * 5'
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - 'ruby-head'
          - 'jruby-9.4'
          - 'truffleruby-23'
          - 'truffleruby-24'
          - 'truffleruby-head'
          - 'truffleruby+graalvm-23'
          - 'truffleruby+graalvm-24'
          - 'truffleruby+graalvm-head'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake spec
